import type { Activity, Application, Artist, ArtistReply, Booking, Lead, Member, Payment, Payout, PortfolioFile, ResolutionCase, Settings } from "@/lib/admin-store";

// Converts between database rows (snake_case columns, see supabase/migrations) and the records
// the admin screens use (src/lib/admin-store.ts). Missing values become safe defaults, so an
// odd row never breaks a screen.

type Row = Record<string, unknown>;

const str = (v: unknown) => (typeof v === "string" ? v : v == null ? "" : String(v));
const opt = (v: unknown) => (v == null || v === "" ? undefined : str(v));
const num = (v: unknown) => (v == null || v === "" || !Number.isFinite(Number(v)) ? undefined : Number(v));
const list = (v: unknown) => (Array.isArray(v) ? v.map(str) : []);
const json = <T>(v: unknown, fallback: T): T => (v == null ? fallback : (v as T));
const nul = <T>(v: T | undefined) => (v === undefined ? null : v);

export const fromRow = {
  application: (r: Row): Application => ({
    id: str(r.id),
    name: str(r.name),
    phone: str(r.phone),
    email: str(r.email),
    city: str(r.city),
    category: str(r.category),
    services: list(r.services),
    experience: str(r.experience),
    languages: list(r.languages),
    bio: str(r.bio),
    links: list(r.links),
    submittedAt: str(r.submitted_at),
    status: str(r.status) as Application["status"],
    meeting: json<Application["meeting"]>(r.meeting, undefined),
    kyc: str(r.kyc) as Application["kyc"],
    notes: json(r.notes, []),
    artistId: opt(r.artist_id),
    portfolio: json<PortfolioFile[]>(r.portfolio, []),
  }),
  artist: (r: Row): Artist => ({
    id: str(r.id),
    name: str(r.name),
    phone: str(r.phone),
    email: str(r.email),
    city: str(r.city),
    category: str(r.category),
    services: list(r.services),
    experience: str(r.experience),
    languages: list(r.languages),
    joinedAt: str(r.joined_at),
    status: str(r.status) as Artist["status"],
    kyc: str(r.kyc) as Artist["kyc"],
    payoutUpi: str(r.payout_upi),
    blockedDates: list(r.blocked_dates),
    notes: json(r.notes, []),
    bio: str(r.bio),
    links: list(r.links),
    portfolio: json<PortfolioFile[]>(r.portfolio, []),
  }),
  reply: (r: Row): ArtistReply & { bookingId: string } => ({
    bookingId: str(r.booking_id),
    artistId: str(r.artist_id),
    status: str(r.status) === "declined" ? "declined" : "quoted",
    quote: num(r.quote),
    note: str(r.note),
    at: str(r.at),
  }),
  booking: (r: Row): Booking => ({
    id: str(r.id),
    requestRef: opt(r.request_ref),
    createdAt: str(r.created_at),
    audience: str(r.audience) === "Business" ? "Business" : "Personal",
    customer: { name: str(r.customer_name), phone: str(r.customer_phone), email: str(r.customer_email) },
    category: str(r.category),
    service: str(r.service),
    event: str(r.event),
    date: str(r.event_date),
    time: str(r.event_time),
    endTime: opt(r.event_end_time),
    city: str(r.city),
    venue: str(r.venue),
    budget: str(r.budget),
    notes: str(r.notes),
    status: str(r.status) as Booking["status"],
    artistId: opt(r.artist_id),
    shortlist: list(r.shortlist),
    quote: num(r.quote),
    advance: num(r.advance),
    delivery: json<Booking["delivery"]>(r.delivery, undefined),
    review: json<Booking["review"]>(r.review, undefined),
    history: json(r.history, []),
    notesLog: json(r.notes_log, []),
  }),
  payment: (r: Row): Payment => ({
    id: str(r.id),
    bookingId: str(r.booking_id),
    amount: num(r.amount) ?? 0,
    utr: str(r.utr),
    payer: str(r.payer),
    reportedAt: str(r.reported_at),
    status: str(r.status) as Payment["status"],
    checkedBy: opt(r.checked_by),
    checkedAt: opt(r.checked_at),
    reason: opt(r.reason),
  }),
  payout: (r: Row): Payout => ({
    id: str(r.id),
    artistId: str(r.artist_id),
    bookingId: str(r.booking_id),
    amount: num(r.amount) ?? 0,
    status: str(r.status) as Payout["status"],
    paidAt: opt(r.paid_at),
    reference: opt(r.reference),
  }),
  lead: (r: Row): Lead => ({
    id: str(r.id),
    createdAt: str(r.created_at),
    name: str(r.name),
    phone: str(r.phone),
    source: str(r.source),
    type: str(r.type) === "Business" ? "Business" : "Personal",
    need: str(r.need),
    city: str(r.city),
    status: str(r.status) as Lead["status"],
    notes: json(r.notes, []),
    bookingId: opt(r.booking_id),
  }),
  case: (r: Row): ResolutionCase => ({
    id: str(r.id),
    createdAt: str(r.created_at),
    role: (["customer", "business", "artist"].includes(str(r.role)) ? str(r.role) : "customer") as ResolutionCase["role"],
    name: str(r.name),
    email: str(r.email),
    phone: str(r.phone),
    bookingRef: str(r.booking_ref),
    issue: str(r.issue),
    incidentDate: str(r.incident_date),
    description: str(r.description),
    outcome: str(r.outcome),
    evidence: list(r.evidence),
    status: str(r.status) as ResolutionCase["status"],
    resolution: opt(r.resolution),
    history: json(r.history, []),
    notes: json(r.notes, []),
  }),
  member: (r: Row): Member => ({
    id: str(r.id),
    name: str(r.name),
    email: str(r.email),
    role: str(r.role) as Member["role"],
    active: r.active !== false,
    twoFactor: r.two_factor === true,
    lastActive: str(r.last_active ?? r.created_at),
  }),
  activity: (r: Row): Activity => ({
    id: str(r.id),
    at: str(r.at),
    by: str(r.by),
    area: str(r.area),
    text: str(r.text),
    target: opt(r.target),
  }),
};

export const toRow = {
  application: (a: Application): Row => ({
    id: a.id,
    name: a.name,
    phone: a.phone,
    email: a.email,
    city: a.city,
    category: a.category,
    services: a.services,
    experience: a.experience,
    languages: a.languages,
    bio: a.bio,
    links: a.links,
    submitted_at: a.submittedAt,
    status: a.status,
    meeting: nul(a.meeting),
    kyc: a.kyc,
    notes: a.notes,
    artist_id: nul(a.artistId),
    portfolio: a.portfolio ?? [],
  }),
  artist: (a: Artist): Row => ({
    id: a.id,
    name: a.name,
    phone: a.phone,
    email: a.email,
    city: a.city,
    category: a.category,
    services: a.services,
    experience: a.experience,
    languages: a.languages,
    joined_at: a.joinedAt,
    status: a.status,
    kyc: a.kyc,
    payout_upi: a.payoutUpi,
    blocked_dates: a.blockedDates,
    notes: a.notes,
    bio: a.bio ?? "",
    links: a.links ?? [],
    portfolio: a.portfolio ?? [],
  }),
  booking: (b: Booking): Row => ({
    id: b.id,
    request_ref: nul(b.requestRef),
    created_at: b.createdAt,
    audience: b.audience,
    customer_name: b.customer.name,
    customer_phone: b.customer.phone,
    customer_email: b.customer.email.trim().toLowerCase(),
    category: b.category,
    service: b.service,
    event: b.event,
    event_date: b.date,
    event_time: b.time,
    event_end_time: b.endTime ?? "",
    city: b.city,
    venue: b.venue,
    budget: b.budget,
    notes: b.notes,
    status: b.status,
    artist_id: nul(b.artistId),
    shortlist: b.shortlist,
    quote: nul(b.quote),
    advance: nul(b.advance),
    delivery: nul(b.delivery),
    review: nul(b.review),
    history: b.history,
    notes_log: b.notesLog,
  }),
  payment: (p: Payment): Row => ({
    id: p.id,
    booking_id: p.bookingId,
    amount: p.amount,
    utr: p.utr,
    payer: p.payer,
    reported_at: p.reportedAt,
    status: p.status,
    checked_by: nul(p.checkedBy),
    checked_at: nul(p.checkedAt),
    reason: nul(p.reason),
  }),
  payout: (p: Payout): Row => ({
    id: p.id,
    artist_id: p.artistId,
    booking_id: p.bookingId,
    amount: p.amount,
    status: p.status,
    paid_at: nul(p.paidAt),
    reference: nul(p.reference),
  }),
  lead: (l: Lead): Row => ({
    id: l.id,
    created_at: l.createdAt,
    name: l.name,
    phone: l.phone,
    source: l.source,
    type: l.type,
    need: l.need,
    city: l.city,
    status: l.status,
    notes: l.notes,
    booking_id: nul(l.bookingId),
  }),
  case: (c: ResolutionCase): Row => ({
    id: c.id,
    created_at: c.createdAt,
    role: c.role,
    name: c.name,
    email: c.email.trim().toLowerCase(),
    phone: c.phone,
    booking_ref: c.bookingRef,
    issue: c.issue,
    incident_date: c.incidentDate,
    description: c.description,
    outcome: c.outcome,
    evidence: c.evidence,
    status: c.status,
    resolution: nul(c.resolution),
    history: c.history,
    notes: c.notes,
  }),
  member: (m: Member): Row => ({
    id: m.id,
    name: m.name,
    email: m.email.trim().toLowerCase(),
    role: m.role,
    active: m.active,
    two_factor: m.twoFactor,
    last_active: m.lastActive || null,
  }),
  activity: (a: Activity): Row => ({ id: a.id, at: a.at, by: a.by, area: a.area, text: a.text, target: nul(a.target) }),
};

export const settingsFromRow = (r: Row | null | undefined): Settings | null => (r?.data ? (r.data as Settings) : null);
